### ISSUE TITLE
ERROR {   err: TypeError: Cannot set property 'init' of undefined

### ISSUE THREAD

**Issue by simsimiSION** [hexojs/hexo-math#142]
ERROR {
  err: TypeError: Cannot set property 'init' of undefined
      at /Users/qaq/Documents/blog/blog/node_modules/mathjax/es5/node-main.js:1:254572
      at Object.<anonymous> (/Users/qaq/Documents/blog/blog/node_modules/mathjax/es5/node-main.js:1:254702)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
      at Module.load (internal/modules/cjs/loader.js:815:32)
      at Function.Module._load (internal/modules/cjs/loader.js:727:14)
      at Module.require (internal/modules/cjs/loader.js:852:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/Users/qaq/Documents/blog/blog/node_modules/hexo-math/lib/mathjax.js:3:18)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
      at Module.load (internal/modules/cjs/loader.js:815:32)
      at Function.Module._load (internal/modules/cjs/loader.js:727:14)
      at Module.require (internal/modules/cjs/loader.js:852:19)
      at req (/Users/qaq/Documents/blog/blog/node_modules/hexo/lib/hexo/index.js:292:23)
      at /Users/qaq/Documents/blog/blog/node_modules/hexo-math/index.js:30:37
      at /Users/qaq/Documents/blog/blog/node_modules/hexo/lib/hexo/index.js:305:14
      at tryCatcher (/Users/qaq/Documents/blog/blog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/qaq/Documents/blog/blog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/qaq/Documents/blog/blog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/qaq/Documents/blog/blog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/qaq/Documents/blog/blog/node_modules/bluebird/js/release/promise.js:729:18)
} Plugin load failed: %s hexo-math

**Comment by themantalope** [comment]
I am also having this issue.

**Comment by eurekazheng** [comment]
我也有这个问题，快修复一下吧

**Comment by azreallem** [comment]
我也是这样的

**Comment by jiangtj** [comment]
https://github.com/mathjax/MathJax-src/pull/696  seems to be a MathJax issue, we need to wait for them to release a new version
