### ISSUE TITLE
每次部署都遇到这种问题

### ISSUE THREAD

**Issue by dhndzwxj** [hexojs/hexo-math#182]
ERROR {
  err: TypeError: Cannot read properties of null (reading 'css')
      at /Users/juncker/dlog/node_modules/hexo-math/index.js:33:20
      at /Users/juncker/dlog/node_modules/hexo/lib/hexo/index.js:305:14
      at tryCatcher (/Users/juncker/dlog/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/juncker/dlog/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/juncker/dlog/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/juncker/dlog/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/juncker/dlog/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/juncker/dlog/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/juncker/dlog/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/juncker/dlog/node_modules/bluebird/js/release/async.js:102:5)
      at Async.drainQueues [as _onImmediate] (/Users/juncker/dlog/node_modules/bluebird/js/release/async.js:15:14)
      at process.processImmediate (node:internal/timers:471:21)
} Plugin load failed: %s hexo-math

**Comment by stevenjoezhang** [comment]
你需要看看 `_config.yml` 里面的 `math` 配置对不对

https://github.com/hexojs/hexo-math#global-options
