### ISSUE TITLE
KaTeX无法渲染aligned环境？

### ISSUE THREAD

**Issue by Tedxz** [hexojs/hexo-math#31]
我用如下代码插入公式，无法正确渲染

```
{% math %}
\begin{aligned}
x =& {[{x_0},{x_1},{x_2},{x_3},{x_4}]^T} \in {{R}^{n + 1}} \\
{w} =& {[{{w}_0},{{w}_1},{{w}_2},{{w}_3},{{w}_4}]^T} \in {{R}^{n + 1}}
\end{aligned}
{% endmath %}
```

运行hexo server报错如下（同一个错误报了两次，只复制了一遍）：

```
ERROR KaTeX parse error: No such environment: aligned at position 15: \begin{aligned}̲
x =& {[{x_0},
ParseError: KaTeX parse error: No such environment: aligned at position 15: \begin{aligned}̲
x =& {[{x_0},
    at new ParseError (D:\Documents\Online\newio\node_modules\katex\src\ParseError.js:29:16)
    at Parser.parseImplicitGroup (D:\Documents\Online\newio\node_modules\katex\src\Parser.js:426:19)
    at Parser.parseAtom (D:\Documents\Online\newio\node_modules\katex\src\Parser.js:281:21)
    at Parser.parseExpression (D:\Documents\Online\newio\node_modules\katex\src\Parser.js:130:25)
    at Parser.parseInput (D:\Documents\Online\newio\node_modules\katex\src\Parser.js:97:27)
    at Parser.parse (D:\Documents\Online\newio\node_modules\katex\src\Parser.js:88:22)
    at parseTree (D:\Documents\Online\newio\node_modules\katex\src\parseTree.js:14:19)
    at Object.renderToString (D:\Documents\Online\newio\node_modules\katex\katex.js:51:16)
    at MathTag._kaTeX (D:\Documents\Online\newio\node_modules\hexo-math\lib\tag\math.js:66:32)
    at MathTag._transform (D:\Documents\Online\newio\node_modules\hexo-math\lib\tag\math.js:51:44)
    at NunjucksBlock.NunjucksTag._run (D:\Documents\Online\newio\node_modules\hexo\lib\extend\tag.js:120:18)
    at NunjucksBlock.run (D:\Documents\Online\newio\node_modules\hexo\lib\extend\tag.js:144:15)
    at root [as rootRenderFunc] (eval at <anonymous> (D:\Documents\Online\newio\node_modules\nunjucks\src\environment.js:564:24), <anonymous>:202:64)
    at Obj.extend.render (D:\Documents\Online\newio\node_modules\nunjucks\src\environment.js:478:15)
    at Obj.extend.renderString (D:\Documents\Online\newio\node_modules\nunjucks\src\environment.js:326:21)
    at D:\Documents\Online\newio\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (D:\Documents\Online\newio\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (D:\Documents\Online\newio\node_modules\bluebird\js\release\promise.js:475:18)
    at new Promise (D:\Documents\Online\newio\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (D:\Documents\Online\newio\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\Documents\Online\newio\node_modules\hexo\lib\hexo\post.js:253:16)
    at D:\Documents\Online\newio\node_modules\hexo\lib\hexo\render.js:65:19
```

**Comment by akfish** [comment]
`aligned` environment was not supported by KaTeX until 0.6.0. This plugin uses older version of KaTeX.

Bumped up to 0.6.0 in 3.0.2. It should be fixed.

**Comment by masszhou** [comment]
I met the problem in hexo-math 3.0.4. I solved this problem by correcting the cdn address in <site_folder>/theme/next/_config.yml
