### ISSUE TITLE
Unhandled rejection TypeError: Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by jacinzhang** [hexojs/hexo-math#36]
1.成功执行命令 `npm install hexo-math --save`

2.执行命令 `hexo math install`，报如下错误

```shell
INFO  [hexo-math] Using engine 'mathjax'
INFO  [hexo-inject] installing hotfix for hexojs/hexo#1791
Unhandled rejection TypeError: Invalid attempt to destructure non-iterable instance
    at /Users/XIN/Source Code/HexoBlog/node_modules/hexo-inject/lib/util.js:7:585
    at parse (/Users/XIN/Source Code/HexoBlog/node_modules/hexo-inject/lib/util.js:32:34)
    at Array.map (native)
    at callsite (/Users/XIN/Source Code/HexoBlog/node_modules/hexo-inject/lib/util.js:52:4)
    at Inject.require (/Users/XIN/Source Code/HexoBlog/node_modules/hexo-inject/lib/mixin/require.js:100:55)
    at Object.require (/Users/XIN/Source Code/HexoBlog/node_modules/hexo-inject/lib/inject.js:65:21)
    at Inject._injectMathJax (/Users/XIN/Source Code/HexoBlog/node_modules/hexo-math/lib/filter/inject.js:43:22)
    at Hexo.tryCatcher (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/XIN/Source Code/HexoBlog/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/reduce.js:145:18)
    at Object.gotAccum (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromiseCtx (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/promise.js:597:10)
    at Async._drainQueue (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/async.js:131:12)
    at Async._drainQueues (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/XIN/Source Code/HexoBlog/node_modules/bluebird/js/release/async.js:16:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by yukityann** [comment]
请问解决了吗？我也遇到了同样的问题
`$ hexo g
INFO  [hexo-math] Using engine 'mathjax'
Unhandled rejection TypeError: Invalid attempt to destructure non-iterable instance
    at C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo-inject\lib\util.js:7:585
    at parse (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo-inject\lib\util.js:32:34)
    at Array.map (<anonymous>)
    at callsite (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo-inject\lib\util.js:52:4)
    at Inject.require (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo-inject\lib\mixin\require.js:100:55)
    at Object.require (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo-inject\lib\inject.js:65:21)
    at Inject._injectMathJax (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo-math\lib\filter\inject.js:43:22)
    at Hexo.tryCatcher (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.each.filter (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\extend\filter.js:63:65)
    at tryCatcher (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
INFO  Start processing
INFO  Files loaded in 619 ms
ERROR C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\themes\landscape\layout\page.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\themes\landscape\layout\_partial\article.ejs:30
    28|         <a href="<%- post.permalink %>#disqus_thread" class="article-comment-link"><%= __('comment') %></a>
    29|       <% } %>
 >> 30|       <%- partial('post/tag') %>
    31|     </footer>
    32|   </div>
    33|   <% if (!index){ %>

C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\themes\landscape\layout\_partial\post\tag.ejs:2
    1| <% if (post.tags && post.tags.length){ %>
 >> 2|   <%- list_tags(post.tags, {
    3|     show_count: false,
    4|     class: 'article-tag'
    5|   }) %>

name is not a function!
TypeError: C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\themes\landscape\layout\page.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\themes\landscape\layout\_partial\article.ejs:30
    28|         <a href="<%- post.permalink %>#disqus_thread" class="article-comment-link"><%= __('comment') %></a>
    29|       <% } %>
 >> 30|       <%- partial('post/tag') %>
    31|     </footer>
    32|   </div>
    33|   <% if (!index){ %>

C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\themes\landscape\layout\_partial\post\tag.ejs:2
    1| <% if (post.tags && post.tags.length){ %>
 >> 2|   <%- list_tags(post.tags, {
    3|     show_count: false,
    4|     class: 'article-tag'
    5|   }) %>

name is not a function!
    at module.exports (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\babel-polyfill\node_modules\core-js\modules\_a-function.js:2:38)
    at Array.sort (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\babel-polyfill\node_modules\core-js\modules\es6.array.sort.js:21:36)
    at Object.listTagsHelper (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\plugins\helper\list_tags.js:24:15)
    at Object.wrapper [as list_tags] (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\lodash\lodash.js:4949:19)
    at eval (eval at compile (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:17)
    at returnedFn (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\theme\view.js:120:22)
    at Theme._View.View.View.renderSync (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\plugins\helper\partial.js:39:15)
    at Object.wrapper [as partial] (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\lodash\lodash.js:4949:19)
    at eval (eval at compile (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:79:17)
    at returnedFn (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\theme\view.js:120:22)
    at Theme._View.View.View.renderSync (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\plugins\helper\partial.js:39:15)
    at Object.wrapper [as partial] (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\lodash\lodash.js:4949:19)
    at eval (eval at compile (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:9:17)
    at returnedFn (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\theme\view.js:124:48)
    at Theme._View.View.View.render (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\theme\view.js:29:15)
    at route.set (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\hexo\lib\hexo\index.js:386:29)
    at tryCatcher (C:\Users\Aoi Yuki\Projects\Blog\AoiYuki\node_modules\bluebird\js\release\util.js:16:23)
`
完全不知道是因为我改了什么。。。

**Comment by ljp215** [comment]
> `

我卸载重装 hexo-math 就好了。

**Comment by stevenjoezhang** [comment]
`hexo-inject` is now deprecated. There is a discussion about it: #130
I'm closing this issue. Please join the discussion there :)
