### ISSUE TITLE
Cannot install hexo-math "Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by zealseeker** [hexojs/hexo-math#85]
Hi, when I was installing hexo-math, it showed that 
```
npm ERR! Cannot read property '0' of undefined
```
I have tried to update npm but the error still exists.

Here is the part of the log:
```
3440 verbose stack TypeError: Cannot read property '0' of undefined
3440 verbose stack     at rmStuff (/usr/local/lib/node_modules/npm/lib/unbuild.js:61:24)
3440 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3440 verbose stack     at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
3440 verbose stack     at lifecycle.then.then (/usr/local/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
3440 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3440 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
3440 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
3440 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
3440 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
3440 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
3440 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
3440 verbose stack     at <anonymous>
3441 verbose cwd /Users/zealseeker/Documents/git/zealseeker-blog
3442 verbose Darwin 18.0.0
3443 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hexo-math" "--save"
3444 verbose node v8.9.3
3445 verbose npm  v6.9.0
3446 error Cannot read property '0' of undefined
3447 verbose exit [ 1, true ]
```

**Comment by zealseeker** [comment]
It seems to be a problem with npm
https://github.com/npm/npm/issues/17858

Now I am closing the issue but still welcome the possible solutions.
